meta:
  version: latest
  name: my-mqtt-connector
  type: mqtt-source
  topic: mqtt-topic
  create-topic: true
mqtt:  
  url: "mqtt://test.mosquitto.org/"  
  topic: "mqtt-to-fluvio"
  client_id: "my_mqtt"
  timeout:
    secs: 30
    nanos: 0
  payload_output_type: json
  # subscribe_delay:    # Optional: delay between CONNECT and SUBSCRIBE
  #   secs: 3           # Recommended when using NATS MQTT bridge
  #   nanos: 0

